import {t,getLanguage} from './i18n.js';
import {overlapsYear,governmentsForYear,coalitionForYear} from './deficit-model.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountEconomy(root,data,initial='deficit'){
 let id=data.series.some(s=>s.id===initial)?initial:'deficit',range=30,year,observer;
 const locale=()=>getLanguage()==='pl'?'pl-PL':'en-GB';
 const label=obj=>obj?.[getLanguage()]||obj?.pl||'';
 const num=(v,d=1)=>new Intl.NumberFormat(locale(),{minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
 const date=v=>new Intl.DateTimeFormat(locale(),{dateStyle:'medium',timeZone:'UTC'}).format(new Date(v));
 const series=()=>data.series.find(s=>s.id===id);
 const rows=()=>series().rows.filter(r=>r.year>series().rows.at(-1).year-range);
 const unit=()=>getLanguage()==='pl'?series().unit:series().unitEn;
 function render(){const s=series(),visible=rows();if(!visible.some(r=>r.year===year))year=visible.at(-1).year;
  root.innerHTML=`<header class="deficit-heading"><div class="eyebrow">${t('economy.eyebrow')}</div><h1>${t('economy.title')}</h1><p>${t('economy.subtitle')}</p></header><div class="economy-layout"><aside class="indicator-sidebar" aria-label="${t('economy.indicators')}"><strong>${t('economy.indicators')}</strong>${data.series.map(item=>`<button type="button" data-indicator="${item.id}" aria-pressed="${item.id===id}"><span>${esc(label(item.label))}</span><small>${num(item.rows.at(-1).value)} ${esc(getLanguage()==='pl'?item.unit:item.unitEn)} · ${item.rows.at(-1).year}</small></button>`).join('')}</aside><div class="economy-content"><section class="deficit-chart-section"><div class="deficit-chart-top"><div><span class="economy-current-label">${visible.at(-1).year} · ${t('economy.latest')}</span><h2>${esc(label(s.title))}</h2><strong class="economy-current">${num(visible.at(-1).value)} <small>${esc(unit())}</small></strong></div><div class="segmented">${[10,20,30].map(n=>`<button type="button" data-range="${n}" aria-pressed="${range===n}">${t('deficit.years',{count:n})}</button>`).join('')}</div></div><div class="deficit-chart-wrap" data-chart></div><div class="chart-caption"><span>${t('economy.hint')}</span><label>${t('deficit.selectYear')} <select data-year>${visible.map(r=>`<option value="${r.year}" ${r.year===year?'selected':''}>${r.year}</option>`).join('')}</select></label></div><div class="year-selection" data-selection></div><p class="indicator-note">${esc(label(s.note))}</p></section><section class="deficit-comparisons"><h2>${t('economy.terms')}</h2><p>${t('economy.termsNote')}</p><div class="term-buttons">${data.terms.filter(term=>visible.some(r=>overlapsYear(term,r.year))).toReversed().map(term=>`<button type="button" data-term="${term.id}"><strong>${t('deficit.term',{term:term.label})}</strong><small>${term.from.slice(0,4)}–${term.to?term.to.slice(0,4):t('deficit.present')}</small></button>`).join('')}</div><div data-term-result></div></section><footer class="deficit-sources"><div><p>${t('economy.updated',{date:date(data.checkedAt)})}</p></div><div><a href="${esc(s.sourceUrl)}" target="_blank" rel="noopener">${esc(s.source)} ↗</a><a href="${esc(data.termsSource)}" target="_blank" rel="noopener">${t('deficit.termsSource')}</a></div></footer></div></div>`;draw();select(year);observer?.disconnect();if(typeof ResizeObserver!=='undefined'){observer=new ResizeObserver(draw);observer.observe(root.querySelector('[data-chart]'));}}
 function draw(){const el=root.querySelector('[data-chart]');if(!el)return;const values=rows(),w=Math.max(250,el.getBoundingClientRect().width||820),h=300,l=58,r=14,top=28,b=42;const min=Math.min(0,...values.map(x=>x.value)),max=Math.max(0,...values.map(x=>x.value)),pad=Math.max(1,(max-min)*.08),lo=min-pad,hi=max+pad,xv=i=>l+i*(w-l-r)/Math.max(1,values.length-1),yv=v=>top+(hi-v)/(hi-lo)*(h-top-b),points=values.map((d,i)=>`${xv(i)},${yv(d.value)}`).join(' '),ticks=[lo,(lo+hi)/2,hi];el.innerHTML=`<svg class="deficit-chart economy-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(label(series().title))}">${ticks.map(v=>`<line x1="${l}" x2="${w-r}" y1="${yv(v)}" y2="${yv(v)}" class="grid-line"/><text x="${l-9}" y="${yv(v)+4}" text-anchor="end">${num(v)}</text>`).join('')}<line x1="${l}" x2="${w-r}" y1="${yv(0)}" y2="${yv(0)}" class="zero-line"/><polyline points="${points}" class="economy-line"/>${values.map((d,i)=>`<circle data-point="${d.year}" cx="${xv(i)}" cy="${yv(d.value)}" r="${d.year===year?6:4}" class="economy-point ${d.year===year?'is-selected':''}"><title>${d.year}: ${num(d.value)} ${esc(unit())}</title></circle>`).join('')}${values.filter((_,i)=>i===0||i===values.length-1||i%Math.ceil(values.length/6)===0).map(d=>`<text x="${xv(values.indexOf(d))}" y="${h-15}" text-anchor="middle">${d.year}</text>`).join('')}</svg>`;}
 function select(y){year=+y;const row=rows().find(r=>r.year===year);if(!row)return;root.querySelector('[data-year]').value=year;root.querySelectorAll('[data-point]').forEach(p=>p.classList.toggle('is-selected',+p.dataset.point===year));const govs=governmentsForYear(data,year),terms=data.terms.filter(term=>overlapsYear(term,year)).map(term=>term.label).join(' / ');root.querySelector('[data-selection]').innerHTML=`<div class="selected-value"><span>${year}</span><strong>${num(row.value)} <small>${esc(unit())}</small></strong><span>${t('deficit.termYear',{terms:terms||'—'})}</span></div><div class="selected-government"><h3>${t('deficit.primeMinisters')}</h3>${govs.map(g=>`<div><strong>${esc(g.name)}</strong><span>${esc(coalitionForYear(g,year,getLanguage()))}</span></div>`).join('')||`<p>${t('deficit.noData')}</p>`}</div>`;}
 function term(termId){const term=data.terms.find(t=>t.id===+termId),full=series().rows.filter(r=>term.from<=`${r.year}-01-01`&&(!term.to||term.to>=`${r.year}-12-31`));const el=root.querySelector('[data-term-result]');if(full.length<2){el.innerHTML=`<p class="term-summary">${t('deficit.insufficient')}</p>`;return;}const first=full[0],last=full.at(-1),delta=last.value-first.value;el.innerHTML=`<div class="term-summary"><strong>${t('deficit.term',{term:term.label})} · ${first.year}–${last.year}</strong><span>${num(first.value)} → ${num(last.value)} ${esc(unit())}</span><b>${delta>0?'+':''}${num(delta)} ${esc(unit())}</b></div>`;}
 function click(e){const chart=e.target.closest('[data-chart]');if(chart){const svg=chart.querySelector('svg'),values=rows(),box=svg.getBoundingClientRect(),width=+svg.getAttribute('viewBox').split(' ')[2],x=(e.clientX-box.left)*width/Math.max(1,box.width),index=Math.max(0,Math.min(values.length-1,Math.round((x-58)/(width-72)*(values.length-1))));select(values[index].year);return;}const button=e.target.closest('button');if(!button)return;if(button.dataset.indicator){id=button.dataset.indicator;range=30;year=null;render();history.replaceState(null,'',`#polska-w-liczbach/${id}`);}else if(button.dataset.range){range=+button.dataset.range;render();}else if(button.dataset.term)term(button.dataset.term);}
 const change=e=>{if(e.target.matches('[data-year]'))select(e.target.value);};const language=()=>render();root.addEventListener('click',click);root.addEventListener('change',change);document.addEventListener('parlament:language',language);render();return()=>{observer?.disconnect();root.removeEventListener('click',click);root.removeEventListener('change',change);document.removeEventListener('parlament:language',language);};
}
